///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BookStoreTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the BookStoreTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("c676db04-1040-4c3f-8ad6-10e632151eda")]
    public partial class BookStoreTestRepository : RepoGenBaseFolder
    {
        static BookStoreTestRepository instance = new BookStoreTestRepository();
        BookStoreTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        BookStoreTestRepositoryFolders.BookStoreAppFolder _bookstore;

        /// <summary>
        /// Gets the singleton class instance representing the BookStoreTestRepository element repository.
        /// </summary>
        [RepositoryFolder("c676db04-1040-4c3f-8ad6-10e632151eda")]
        public static BookStoreTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public BookStoreTestRepository() 
            : base("BookStoreTestRepository", "/", null, 0, false, "c676db04-1040-4c3f-8ad6-10e632151eda", ".\\RepositoryImages\\BookStoreTestRepositoryc676db04.rximgres")
        {
            _applicationundertest = new BookStoreTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _bookstore = new BookStoreTestRepositoryFolders.BookStoreAppFolder(this);
        }

#region Variables

        string _txtErrorMess = "^Thông\\ tin\\ không\\ được\\ để\\ t";

        /// <summary>
        /// Gets or sets the value of variable txtErrorMess.
        /// </summary>
        [TestVariable("3a78eec1-ae5c-41e4-b38d-76fa734f062d")]
        public string txtErrorMess
        {
            get { return _txtErrorMess; }
            set { _txtErrorMess = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c676db04-1040-4c3f-8ad6-10e632151eda")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("6133c113-3cd9-49e0-8ba1-402e4fbb6b9e")]
        public virtual BookStoreTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The BookStore folder.
        /// </summary>
        [RepositoryFolder("a4180362-6a84-4556-9da7-83dbc77601a9")]
        public virtual BookStoreTestRepositoryFolders.BookStoreAppFolder BookStore
        {
            get { return _bookstore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class BookStoreTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("6133c113-3cd9-49e0-8ba1-402e4fbb6b9e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            BookStoreTestRepositoryFolders.SomeContainer1Folder _somecontainer1;
            RepoItemInfo _partcontenthostInfo;
            RepoItemInfo _textboxInfo;
            RepoItemInfo _mậtkhẩuInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _partcontenthost1Info;
            RepoItemInfo _đăngnhậpInfo;
            RepoItemInfo _mậthoặctaikhoảnkhongđungInfo;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _button1Info;
            ButtonOpenInfoClass _buttonopenInfo;
            RepoItemInfo _text65535Info;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='BookStore']", parentFolder, 1000, null, false, "6133c113-3cd9-49e0-8ba1-402e4fbb6b9e", "")
            {
                _somecontainer1 = new BookStoreTestRepositoryFolders.SomeContainer1Folder(this);
                _partcontenthostInfo = new RepoItemInfo(this, "PARTContentHost", "?/?/container[@automationid='PART_ContentHost']", 30000, null, "d25f9711-466f-443d-9ce3-ec9d28ae30ee");
                _textboxInfo = new RepoItemInfo(this, "TextBox", "text[@classname='TextBox']", 30000, null, "1794b37f-668a-4f39-b561-bc887964f76c");
                _mậtkhẩuInfo = new RepoItemInfo(this, "MậtKhẩu", "?/?/text[@name='Mật khẩu']", 30000, null, "968c6cf7-0932-44c8-8269-5f5af98f5e67");
                _passwordInfo = new RepoItemInfo(this, "Password", "text[@automationid='Password']", 30000, null, "e9190c4d-287a-4dc3-86dd-d27e04c14c0f");
                _partcontenthost1Info = new RepoItemInfo(this, "PARTContentHost1", "text[@automationid='Password']/container[@automationid='PART_ContentHost']", 30000, null, "66562a7a-826d-488d-90f0-93d20b9b6606");
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", "button[@name='Đăng nhập']", 30000, null, "c50bdcac-bd82-4818-896a-6c53f7ab0c75");
                _mậthoặctaikhoảnkhongđungInfo = new RepoItemInfo(this, "MậtHoặcTaiKhoảnKhongĐung", "text[@name~'^Mật\\ hoặc\\ tài\\ khoản\\ không\\ ']", 30000, null, "bef9e9c7-6011-4b5b-8035-8ded46cc9cea");
                _buttonInfo = new RepoItemInfo(this, "Button", "button[@helptext='Khuyến mãi']", 30000, null, "aef1086d-e112-4138-bd75-ec7ed51711a9");
                _button1Info = new RepoItemInfo(this, "Button1", "?/?/button[@helptext='Thoát']", 30000, null, "31fab4ff-b418-4016-a854-e50d1c2e9328");
                _buttonopenInfo = new ButtonOpenInfoClass(this);
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", 3000, null, "7850d7de-78f5-4bd3-89ad-1e9c137519ff");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 3000, null, "2d0ed5ae-c3ed-4fd9-8e70-230a4b88eb10");
            }

            /// <summary>
            /// The ButtonOpenInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("112c2f47-51e0-46a5-85c8-933bd9396cd5")]
            public class ButtonOpenInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ButtonOpenInfoClass class constructor.
                /// </summary>
                public ButtonOpenInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ButtonOpen", "button[@text='&Open']", 3000, null, "112c2f47-51e0-46a5-85c8-933bd9396cd5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("27ca6083-07bc-4557-bd3c-15ae548f5ae6")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("27ca6083-07bc-4557-bd3c-15ae548f5ae6");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("27ca6083-07bc-4557-bd3c-15ae548f5ae6")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("27ca6083-07bc-4557-bd3c-15ae548f5ae6", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6133c113-3cd9-49e0-8ba1-402e4fbb6b9e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6133c113-3cd9-49e0-8ba1-402e4fbb6b9e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost item.
            /// </summary>
            [RepositoryItem("d25f9711-466f-443d-9ce3-ec9d28ae30ee")]
            public virtual Ranorex.Container PARTContentHost
            {
                get
                {
                    return _partcontenthostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost item info.
            /// </summary>
            [RepositoryItemInfo("d25f9711-466f-443d-9ce3-ec9d28ae30ee")]
            public virtual RepoItemInfo PARTContentHostInfo
            {
                get
                {
                    return _partcontenthostInfo;
                }
            }

            /// <summary>
            /// The TextBox item.
            /// </summary>
            [RepositoryItem("1794b37f-668a-4f39-b561-bc887964f76c")]
            public virtual Ranorex.Text TextBox
            {
                get
                {
                    return _textboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextBox item info.
            /// </summary>
            [RepositoryItemInfo("1794b37f-668a-4f39-b561-bc887964f76c")]
            public virtual RepoItemInfo TextBoxInfo
            {
                get
                {
                    return _textboxInfo;
                }
            }

            /// <summary>
            /// The MậtKhẩu item.
            /// </summary>
            [RepositoryItem("968c6cf7-0932-44c8-8269-5f5af98f5e67")]
            public virtual Ranorex.Text MậtKhẩu
            {
                get
                {
                    return _mậtkhẩuInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MậtKhẩu item info.
            /// </summary>
            [RepositoryItemInfo("968c6cf7-0932-44c8-8269-5f5af98f5e67")]
            public virtual RepoItemInfo MậtKhẩuInfo
            {
                get
                {
                    return _mậtkhẩuInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("e9190c4d-287a-4dc3-86dd-d27e04c14c0f")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("e9190c4d-287a-4dc3-86dd-d27e04c14c0f")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The PARTContentHost1 item.
            /// </summary>
            [RepositoryItem("66562a7a-826d-488d-90f0-93d20b9b6606")]
            public virtual Ranorex.Container PARTContentHost1
            {
                get
                {
                    return _partcontenthost1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PARTContentHost1 item info.
            /// </summary>
            [RepositoryItemInfo("66562a7a-826d-488d-90f0-93d20b9b6606")]
            public virtual RepoItemInfo PARTContentHost1Info
            {
                get
                {
                    return _partcontenthost1Info;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("c50bdcac-bd82-4818-896a-6c53f7ab0c75")]
            public virtual Ranorex.Button ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("c50bdcac-bd82-4818-896a-6c53f7ab0c75")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }

            /// <summary>
            /// The MậtHoặcTaiKhoảnKhongĐung item.
            /// </summary>
            [RepositoryItem("bef9e9c7-6011-4b5b-8035-8ded46cc9cea")]
            public virtual Ranorex.Text MậtHoặcTaiKhoảnKhongĐung
            {
                get
                {
                    return _mậthoặctaikhoảnkhongđungInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MậtHoặcTaiKhoảnKhongĐung item info.
            /// </summary>
            [RepositoryItemInfo("bef9e9c7-6011-4b5b-8035-8ded46cc9cea")]
            public virtual RepoItemInfo MậtHoặcTaiKhoảnKhongĐungInfo
            {
                get
                {
                    return _mậthoặctaikhoảnkhongđungInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("aef1086d-e112-4138-bd75-ec7ed51711a9")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("aef1086d-e112-4138-bd75-ec7ed51711a9")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("31fab4ff-b418-4016-a854-e50d1c2e9328")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("31fab4ff-b418-4016-a854-e50d1c2e9328")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("112c2f47-51e0-46a5-85c8-933bd9396cd5")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("112c2f47-51e0-46a5-85c8-933bd9396cd5")]
            public virtual ButtonOpenInfoClass ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("7850d7de-78f5-4bd3-89ad-1e9c137519ff")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("7850d7de-78f5-4bd3-89ad-1e9c137519ff")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("2d0ed5ae-c3ed-4fd9-8e70-230a4b88eb10")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("2d0ed5ae-c3ed-4fd9-8e70-230a4b88eb10")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 folder.
            /// </summary>
            [RepositoryFolder("9f394908-e5af-4bcf-aa4a-46f14e3fc125")]
            public virtual BookStoreTestRepositoryFolders.SomeContainer1Folder SomeContainer1
            {
                get { return _somecontainer1; }
            }
        }

        /// <summary>
        /// The SomeContainer1Folder folder.
        /// </summary>
        [RepositoryFolder("9f394908-e5af-4bcf-aa4a-46f14e3fc125")]
        public partial class SomeContainer1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _tenđăngnhậpInfo;
            RepoItemInfo _mậtkhẩu1Info;
            RepoItemInfo _somecontainerInfo;
            RepoItemInfo _thongtinkhongđượcđểtrốngInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _someelement1Info;
            RepoItemInfo _mậthoặctaikhoảnkhongđungInfo;
            RepoItemInfo _somecontainer1Info;
            RepoItemInfo _someelement2Info;
            RepoItemInfo _timkiếmInfo;
            RepoItemInfo _somecontainer2Info;
            RepoItemInfo _khongtimthấysachInfo;
            SomePictureInfoClass _somepictureInfo;
            RepoItemInfo _toithấyhoavangtrencỏxanhInfo;
            RepoItemInfo _somecontainer3Info;
            RepoItemInfo _somecontainer4Info;
            RepoItemInfo _somecontainer5Info;
            SachMớiInfoClass _sachmớiInfo;
            RepoItemInfo _someelement3Info;
            RepoItemInfo _tensachInfo;
            RepoItemInfo _toggletemplaterootInfo;
            RepoItemInfo _tentacgiảInfo;
            RepoItemInfo _toggletemplateroot1Info;
            RepoItemInfo _toggletemplateroot2Info;
            RepoItemInfo _text50000Info;
            RepoItemInfo _someelement4Info;
            RepoItemInfo _somecontainer6Info;
            PicturesInfoClass _picturesInfo;
            BaselineImageInfoClass _baselineimageInfo;
            ThemInfoClass _themInfo;
            RepoItemInfo _somecontainer7Info;
            RepoItemInfo _somecontainer8Info;
            BorderInfoClass _borderInfo;
            SomeContainer9InfoClass _somecontainer9Info;
            RepoItemInfo _somecontainer10Info;
            RepoItemInfo _somecontainer11Info;
            RepoItemInfo _pictures1Info;

            /// <summary>
            /// Creates a new SomeContainer1  folder.
            /// </summary>
            public SomeContainer1Folder(RepoGenBaseFolder parentFolder) :
                    base("SomeContainer1", ".//container", parentFolder, 1000, null, false, "9f394908-e5af-4bcf-aa4a-46f14e3fc125", "")
            {
                _tenđăngnhậpInfo = new RepoItemInfo(this, "TenĐăngNhập", "element/?/?/element[@automationid='ContentPresenter']/container/container[2]/container//element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/element[@automationid='Hint']/container/element[@automationid='FloatingHintTextBlock']/?/?/text[@caption='Tên đăng nhập']", 30000, null, "4dc29e2f-e1fa-4b0a-9e8a-54e69cb0c976");
                _mậtkhẩu1Info = new RepoItemInfo(this, "MậtKhẩu1", "element/?/?/element[@automationid='ContentPresenter']/container/container[2]/container/text[@automationid='Password']/?/?/element[@automationid='passwordFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='passwordFieldGrid']/element[@automationid='Hint']/?/?/element[@automationid='FloatingHintTextBlock']/?/?/text[@caption='Mật khẩu']", 30000, null, "0c12597f-59e1-413e-a52d-13e3444e8c3b");
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", "element/container/element[@automationid='ContentPresenter']/container/container[2]/container/button[@text='Đăng nhập']//container[@caption='']", 30000, null, "a12452fe-a4f9-438c-a4ba-67bc546c4fc9");
                _thongtinkhongđượcđểtrốngInfo = new RepoItemInfo(this, "ThongTinKhongĐượcĐểTrống", "element/?/?/element[@automationid='ContentPresenter']/container/container[2]/text[@text=$txtErrorMess]", 30000, null, "aaa14d81-c28b-45a3-88e2-0259893da8fb");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "element[@automationid='PART_ScrollContentPresenter']/element[1]", 30000, null, "ba9a5da9-a937-4a18-a8b6-b91fd3948123");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", "element[@automationid='PART_ScrollContentPresenter']/element[1]", 30000, null, "55f9dfcc-6400-4ade-a0a3-e8e4e4739c0e");
                _mậthoặctaikhoảnkhongđungInfo = new RepoItemInfo(this, "MậtHoặcTaiKhoảnKhongĐung", "element/?/?/element[@automationid='ContentPresenter']/container/container[2]/text[@caption~'^Mật\\ hoặc\\ tài\\ khoản\\ không\\ ']", 30000, null, "3e87d557-eac6-4b0a-9ab2-5686c45e5344");
                _somecontainer1Info = new RepoItemInfo(this, "SomeContainer1", "container[2]/container[@automationid='GridMenu']/container[3]/container[2]/button[1]//container[@caption='']", 1000, true, "b2098fc0-a5b9-44ae-8b50-17d1e6cef3bb");
                _someelement2Info = new RepoItemInfo(this, "SomeElement2", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/container[1]/?/?/container/element[@automationid='ContentPresenter']/container/container[1]//element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/container[@automationid='PART_ContentHost']/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/element[1]", 30000, null, "e3afce40-34a1-4388-8c93-10806adb8eb4");
                _timkiếmInfo = new RepoItemInfo(this, "TimKiếm", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/container[1]/?/?/container/element[@automationid='ContentPresenter']/container/container[1]/?/?/container/element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/element[@automationid='Hint']/?/?/element[@automationid='SimpleHintTextBlock']/?/?/text[@caption='Tìm kiếm']", 30000, null, "92030474-0bf6-49eb-a8bc-6a932b113742");
                _somecontainer2Info = new RepoItemInfo(this, "SomeContainer2", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/?/?/element/container/container[2]/container[1]/?/?/container/element[@automationid='ContentPresenter']/container/container[1]/button/container//container[@caption='']", 30000, null, "55c1aaf1-79b9-4db5-8ed0-e60102babebf");
                _khongtimthấysachInfo = new RepoItemInfo(this, "KhongTimThấySach", "container[2]/container[2]/container/?/?/element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/?/?/element/container/container[2]/container[2]/text[@caption='Không tìm thấy sách']", 1000, null, "d0efef63-62a4-4c33-bc6e-c4e981477d37");
                _somepictureInfo = new SomePictureInfoClass(this);
                _toithấyhoavangtrencỏxanhInfo = new RepoItemInfo(this, "ToiThấyHoaVangTrenCỏXanh", "container[2]/container[2]/container/?/?/element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/container[2]/list/container/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/?/?/container[@caption='']/listitem[@index='1']/element[@automationid='Bd']/element/container/container/container/container/text[@caption~'^Tôi\\ Thấy\\ Hoa\\ Vàng\\ Trên\\ Cỏ']", 30000, null, "45ea85ac-676f-4143-85fe-7d47cf878615");
                _somecontainer3Info = new RepoItemInfo(this, "SomeContainer3", "container[2]/container[@automationid='GridMenu']/container[3]/container[2]/button[7]//container[@caption='']", 30000, null, "182493b6-736d-4e2c-8df1-17a4573b82e9");
                _somecontainer4Info = new RepoItemInfo(this, "SomeContainer4", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/?/?/element/container/container[2]/container[2]/list/container/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/?/?/container[@caption='']/listitem[@index='1']/element[@automationid='Bd']/element/container/container", 30000, null, "14cb6e34-68ea-4122-badd-5ecec9f3be6a");
                _somecontainer5Info = new RepoItemInfo(this, "SomeContainer5", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/?/?/element/container/container[2]/container[2]/list/container/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/?/?/container[@caption='']/listitem[@index='0']/element[@automationid='Bd']/element/container/container", 100, null, "ab0242ab-8e42-48b4-8822-d740a881674d");
                _sachmớiInfo = new SachMớiInfoClass(this);
                _someelement3Info = new RepoItemInfo(this, "SomeElement3", "container[2]/container[2]/container[2]/container/container[1]/container[1]//element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/container[@automationid='PART_ContentHost']/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/element[1]", 3000, null, "66af9f4e-bb76-49b6-9538-6b41893febaa");
                _tensachInfo = new RepoItemInfo(this, "TenSach", "container[2]/container[2]/container[2]/container/container[1]/container[1]//element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/element[@automationid='Hint']/?/?/element[@automationid='SimpleHintTextBlock']/?/?/text[@caption='Tên sách']", 3000, null, "b369f7df-c522-480d-b98e-99d5d93e2f8b");
                _toggletemplaterootInfo = new RepoItemInfo(this, "ToggleTemplateRoot", "container[2]/container[2]/container[2]/container/container[1]/container[3]/combobox/container[@automationid='templateRoot']/container[@automationid='InnerRoot']/checkbox[@automationid='toggleButton']/?/?/element[@automationid='ToggleTemplateRoot']", 3000, null, "f1626129-8f81-46ea-bfe6-7ff855d09c8f");
                _tentacgiảInfo = new RepoItemInfo(this, "TenTacGiả", "container[2]/container[2]/container[2]/container/container[1]/container[2]//element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/element[@automationid='Hint']/?/?/element[@automationid='SimpleHintTextBlock']/?/?/text[@caption='Tên tác giả']", 3000, null, "f724989a-619b-4908-8466-27003022f38d");
                _toggletemplateroot1Info = new RepoItemInfo(this, "ToggleTemplateRoot1", "container[2]/container[2]/container[2]/container/container[1]/container[4]/combobox/container[@automationid='templateRoot']/container[@automationid='InnerRoot']/checkbox[@automationid='toggleButton']/?/?/element[@automationid='ToggleTemplateRoot']", 3000, null, "3b6a31e9-0e35-4f01-af4a-d395ff261887");
                _toggletemplateroot2Info = new RepoItemInfo(this, "ToggleTemplateRoot2", "container[2]/container[2]/container[2]/container/container[1]/container[5]/combobox/container[@automationid='templateRoot']/container[@automationid='InnerRoot']/checkbox[@automationid='toggleButton']/?/?/element[@automationid='ToggleTemplateRoot']", 3000, null, "8e9b59ce-1ebc-40bf-8b5c-a2e10f482e52");
                _text50000Info = new RepoItemInfo(this, "Text50000", "container[2]/container[2]/container[2]/container//element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/element[@automationid='Hint']/?/?/element[@automationid='SimpleHintTextBlock']/?/?/text[@caption='50000']", 3000, null, "4d588659-1e53-41d5-b25a-a5d1e9c666df");
                _someelement4Info = new RepoItemInfo(this, "SomeElement4", "container[2]/container[2]/container[2]//text[@caption='']/container/element[@automationid='textFieldBoxBorder']/?/?/element[@automationid='border']/container[@automationid='textFieldGrid']/container[@automationid='PART_ContentHost']/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/element[1]", 3000, null, "dfa34568-bd8a-4e4c-a5ee-7a8cf94f4822");
                _somecontainer6Info = new RepoItemInfo(this, "SomeContainer6", "container[2]/container[2]/container[2]/element/?/?/element[@automationid='ContentPresenter']/?/?/button//container[@caption='']", 3000, null, "22b5bb61-0619-4a4e-96c8-7a7f86030c8e");
                _picturesInfo = new PicturesInfoClass(this);
                _baselineimageInfo = new BaselineImageInfoClass(this);
                _themInfo = new ThemInfoClass(this);
                _somecontainer7Info = new RepoItemInfo(this, "SomeContainer7", "container[2]/container[2]/container[3]/button[@text='Nhập sách']//container[@caption='']", 3000, null, "bea66fb8-4515-46a3-92d5-d11bab30d942");
                _somecontainer8Info = new RepoItemInfo(this, "SomeContainer8", "container[2]/container[2]/container[3]/element/?/?/element[@automationid='ContentPresenter']/list/container/container/container/element[@automationid='PART_ScrollContentPresenter']/?/?/container", 3000, null, "9f0f271e-f4b0-449a-b9ae-7396d4fc582c");
                _borderInfo = new BorderInfoClass(this);
                _somecontainer9Info = new SomeContainer9InfoClass(this);
                _somecontainer10Info = new RepoItemInfo(this, "SomeContainer10", "container[2]/container[2]/container[3]/container/button[@text='Thêm']//container[@caption='']", 3000, null, "4209e6ce-173c-4140-9483-42573f277a93");
                _somecontainer11Info = new RepoItemInfo(this, "SomeContainer11", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/container[2]/element[2]/container/element[@automationid='ContentPresenter']/container/container/button[1]/container//container[@caption='']", 3000, null, "20e549b7-287f-4fa1-afa8-35a1085f242e");
                _pictures1Info = new RepoItemInfo(this, "Pictures1", "element[1]/?/?/tree[@controlid='100']/treeitem[@text='Quick access']/treeitem[@text='Pictures']", 3000, null, "c1b34755-02f1-4065-ae89-6aee094f6d1a");
            }

            /// <summary>
            /// The SomePictureInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("ff390c62-c998-42eb-b5f7-51178c4be702")]
            public class SomePictureInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SomePictureInfoClass class constructor.
                /// </summary>
                public SomePictureInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SomePicture", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/?/?/element/container/container[2]/container[2]/list/container/container[@automationid='Grid']/element[@automationid='PART_ScrollContentPresenter']/?/?/container[@caption='']/listitem[@index='0']/element[@automationid='Bd']//picture", 100, false, "ff390c62-c998-42eb-b5f7-51178c4be702")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("8044e44b-59d7-4f84-961d-8c1fcc30212f")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("8044e44b-59d7-4f84-961d-8c1fcc30212f");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("8044e44b-59d7-4f84-961d-8c1fcc30212f")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("8044e44b-59d7-4f84-961d-8c1fcc30212f", cropRect);
                }
            }

            /// <summary>
            /// The SachMớiInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9c2cb7ab-f454-44cb-a73d-9a2e6cf9f4c5")]
            public class SachMớiInfoClass : RepoItemInfo
            {
                /// <summary>
                /// SachMớiInfoClass class constructor.
                /// </summary>
                public SachMớiInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SachMới", "container[2]/container[2]//element[@automationid='PART_FrameCP']/container/element/element/container/container[2]/?/?/element[@automationid='PART_FrameCP']/container/?/?/element/container/container[2]/container[2]/element[2]/container/element[@automationid='ContentPresenter']/container/container/button[1]/container/element[2]/container//text[@caption='Sách mới']", 3000, null, "9c2cb7ab-f454-44cb-a73d-9a2e6cf9f4c5")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e6c43a60-83f8-4858-853e-2410e45c2808")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e6c43a60-83f8-4858-853e-2410e45c2808");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e6c43a60-83f8-4858-853e-2410e45c2808")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e6c43a60-83f8-4858-853e-2410e45c2808", cropRect);
                }
            }

            /// <summary>
            /// The PicturesInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("983d6328-b834-4899-aea2-4665c311faf1")]
            public class PicturesInfoClass : RepoItemInfo
            {
                /// <summary>
                /// PicturesInfoClass class constructor.
                /// </summary>
                public PicturesInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Pictures", "element[1]/?/?/tree[@controlid='100']/?/?/treeitem[@text='This PC']/treeitem[@text='Pictures']", 3000, null, "983d6328-b834-4899-aea2-4665c311faf1")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("f19fe8e6-a09b-469a-a4a4-7206bea9e717")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("f19fe8e6-a09b-469a-a4a4-7206bea9e717");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f19fe8e6-a09b-469a-a4a4-7206bea9e717")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f19fe8e6-a09b-469a-a4a4-7206bea9e717", cropRect);
                }
            }

            /// <summary>
            /// The BaselineImageInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("c9029e1a-af51-4e87-97d1-f3e765790316")]
            public class BaselineImageInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BaselineImageInfoClass class constructor.
                /// </summary>
                public BaselineImageInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "BaselineImage", "?/?/listitem[@automationid='5']/picture[@automationid='BaselineImage']", 3000, null, "c9029e1a-af51-4e87-97d1-f3e765790316")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("bf08a380-4f8c-423d-9b13-c41c4fd02a75")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("bf08a380-4f8c-423d-9b13-c41c4fd02a75");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("bf08a380-4f8c-423d-9b13-c41c4fd02a75")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("bf08a380-4f8c-423d-9b13-c41c4fd02a75", cropRect);
                }
            }

            /// <summary>
            /// The ThemInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("955aae91-2388-40bc-8feb-9b446b6deb02")]
            public class ThemInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ThemInfoClass class constructor.
                /// </summary>
                public ThemInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Them", "container[2]/container[2]/container[3]/container/button[@text='Thêm']//text[@caption='Thêm']", 3000, null, "955aae91-2388-40bc-8feb-9b446b6deb02")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("c69de2ee-78c0-4770-abed-84a4cc20a7be")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("c69de2ee-78c0-4770-abed-84a4cc20a7be");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("c69de2ee-78c0-4770-abed-84a4cc20a7be")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("c69de2ee-78c0-4770-abed-84a4cc20a7be", cropRect);
                }
            }

            /// <summary>
            /// The BorderInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9f5b10a7-e413-4289-ae5a-d74103cff468")]
            public class BorderInfoClass : RepoItemInfo
            {
                /// <summary>
                /// BorderInfoClass class constructor.
                /// </summary>
                public BorderInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Border", "container[@automationid='ucControlBar']/?/?/element/container/?/?/container/element[2]/element/container/container[1]/button[3]/container/element[1]/element[@automationid='border']", 3000, null, "9f5b10a7-e413-4289-ae5a-d74103cff468")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("35580f9f-c9d8-402b-9ad4-29d4f3309923")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("35580f9f-c9d8-402b-9ad4-29d4f3309923");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("35580f9f-c9d8-402b-9ad4-29d4f3309923")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("35580f9f-c9d8-402b-9ad4-29d4f3309923", cropRect);
                }
            }

            /// <summary>
            /// The SomeContainer9InfoClass folder.
            /// </summary>
            [RepositoryItemInfo("9154ca19-1086-439b-940d-528d7c683df6")]
            public class SomeContainer9InfoClass : RepoItemInfo
            {
                /// <summary>
                /// SomeContainer9InfoClass class constructor.
                /// </summary>
                public SomeContainer9InfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "SomeContainer9", "container[2]/container[@automationid='GridMenu']/container[3]/container[2]/button[2]//container[@caption='']", 3000, null, "9154ca19-1086-439b-940d-528d7c683df6")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("3738d19d-81e8-4ae0-8181-ae8c25024982")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("3738d19d-81e8-4ae0-8181-ae8c25024982");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3738d19d-81e8-4ae0-8181-ae8c25024982")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3738d19d-81e8-4ae0-8181-ae8c25024982", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f394908-e5af-4bcf-aa4a-46f14e3fc125")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f394908-e5af-4bcf-aa4a-46f14e3fc125")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TenĐăngNhập item.
            /// </summary>
            [RepositoryItem("4dc29e2f-e1fa-4b0a-9e8a-54e69cb0c976")]
            public virtual Ranorex.Text TenĐăngNhập
            {
                get
                {
                    return _tenđăngnhậpInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TenĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("4dc29e2f-e1fa-4b0a-9e8a-54e69cb0c976")]
            public virtual RepoItemInfo TenĐăngNhậpInfo
            {
                get
                {
                    return _tenđăngnhậpInfo;
                }
            }

            /// <summary>
            /// The MậtKhẩu1 item.
            /// </summary>
            [RepositoryItem("0c12597f-59e1-413e-a52d-13e3444e8c3b")]
            public virtual Ranorex.Text MậtKhẩu1
            {
                get
                {
                    return _mậtkhẩu1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MậtKhẩu1 item info.
            /// </summary>
            [RepositoryItemInfo("0c12597f-59e1-413e-a52d-13e3444e8c3b")]
            public virtual RepoItemInfo MậtKhẩu1Info
            {
                get
                {
                    return _mậtkhẩu1Info;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("a12452fe-a4f9-438c-a4ba-67bc546c4fc9")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("a12452fe-a4f9-438c-a4ba-67bc546c4fc9")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }

            /// <summary>
            /// The ThongTinKhongĐượcĐểTrống item.
            /// </summary>
            [RepositoryItem("aaa14d81-c28b-45a3-88e2-0259893da8fb")]
            public virtual Ranorex.Text ThongTinKhongĐượcĐểTrống
            {
                get
                {
                    return _thongtinkhongđượcđểtrốngInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ThongTinKhongĐượcĐểTrống item info.
            /// </summary>
            [RepositoryItemInfo("aaa14d81-c28b-45a3-88e2-0259893da8fb")]
            public virtual RepoItemInfo ThongTinKhongĐượcĐểTrốngInfo
            {
                get
                {
                    return _thongtinkhongđượcđểtrốngInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("ba9a5da9-a937-4a18-a8b6-b91fd3948123")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("ba9a5da9-a937-4a18-a8b6-b91fd3948123")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("55f9dfcc-6400-4ade-a0a3-e8e4e4739c0e")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("55f9dfcc-6400-4ade-a0a3-e8e4e4739c0e")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }

            /// <summary>
            /// The MậtHoặcTaiKhoảnKhongĐung item.
            /// </summary>
            [RepositoryItem("3e87d557-eac6-4b0a-9ab2-5686c45e5344")]
            public virtual Ranorex.Text MậtHoặcTaiKhoảnKhongĐung
            {
                get
                {
                    return _mậthoặctaikhoảnkhongđungInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MậtHoặcTaiKhoảnKhongĐung item info.
            /// </summary>
            [RepositoryItemInfo("3e87d557-eac6-4b0a-9ab2-5686c45e5344")]
            public virtual RepoItemInfo MậtHoặcTaiKhoảnKhongĐungInfo
            {
                get
                {
                    return _mậthoặctaikhoảnkhongđungInfo;
                }
            }

            /// <summary>
            /// The SomeContainer1 item.
            /// </summary>
            [RepositoryItem("b2098fc0-a5b9-44ae-8b50-17d1e6cef3bb")]
            public virtual Ranorex.Container SomeContainer1
            {
                get
                {
                    return _somecontainer1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer1 item info.
            /// </summary>
            [RepositoryItemInfo("b2098fc0-a5b9-44ae-8b50-17d1e6cef3bb")]
            public virtual RepoItemInfo SomeContainer1Info
            {
                get
                {
                    return _somecontainer1Info;
                }
            }

            /// <summary>
            /// The SomeElement2 item.
            /// </summary>
            [RepositoryItem("e3afce40-34a1-4388-8c93-10806adb8eb4")]
            public virtual Ranorex.Unknown SomeElement2
            {
                get
                {
                    return _someelement2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement2 item info.
            /// </summary>
            [RepositoryItemInfo("e3afce40-34a1-4388-8c93-10806adb8eb4")]
            public virtual RepoItemInfo SomeElement2Info
            {
                get
                {
                    return _someelement2Info;
                }
            }

            /// <summary>
            /// The TimKiếm item.
            /// </summary>
            [RepositoryItem("92030474-0bf6-49eb-a8bc-6a932b113742")]
            public virtual Ranorex.Text TimKiếm
            {
                get
                {
                    return _timkiếmInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TimKiếm item info.
            /// </summary>
            [RepositoryItemInfo("92030474-0bf6-49eb-a8bc-6a932b113742")]
            public virtual RepoItemInfo TimKiếmInfo
            {
                get
                {
                    return _timkiếmInfo;
                }
            }

            /// <summary>
            /// The SomeContainer2 item.
            /// </summary>
            [RepositoryItem("55c1aaf1-79b9-4db5-8ed0-e60102babebf")]
            public virtual Ranorex.Container SomeContainer2
            {
                get
                {
                    return _somecontainer2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer2 item info.
            /// </summary>
            [RepositoryItemInfo("55c1aaf1-79b9-4db5-8ed0-e60102babebf")]
            public virtual RepoItemInfo SomeContainer2Info
            {
                get
                {
                    return _somecontainer2Info;
                }
            }

            /// <summary>
            /// The KhongTimThấySach item.
            /// </summary>
            [RepositoryItem("d0efef63-62a4-4c33-bc6e-c4e981477d37")]
            public virtual Ranorex.Text KhongTimThấySach
            {
                get
                {
                    return _khongtimthấysachInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The KhongTimThấySach item info.
            /// </summary>
            [RepositoryItemInfo("d0efef63-62a4-4c33-bc6e-c4e981477d37")]
            public virtual RepoItemInfo KhongTimThấySachInfo
            {
                get
                {
                    return _khongtimthấysachInfo;
                }
            }

            /// <summary>
            /// The SomePicture item.
            /// </summary>
            [RepositoryItem("ff390c62-c998-42eb-b5f7-51178c4be702")]
            public virtual Ranorex.Picture SomePicture
            {
                get
                {
                    return _somepictureInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The SomePicture item info.
            /// </summary>
            [RepositoryItemInfo("ff390c62-c998-42eb-b5f7-51178c4be702")]
            public virtual SomePictureInfoClass SomePictureInfo
            {
                get
                {
                    return _somepictureInfo;
                }
            }

            /// <summary>
            /// The ToiThấyHoaVangTrenCỏXanh item.
            /// </summary>
            [RepositoryItem("45ea85ac-676f-4143-85fe-7d47cf878615")]
            public virtual Ranorex.Text ToiThấyHoaVangTrenCỏXanh
            {
                get
                {
                    return _toithấyhoavangtrencỏxanhInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ToiThấyHoaVangTrenCỏXanh item info.
            /// </summary>
            [RepositoryItemInfo("45ea85ac-676f-4143-85fe-7d47cf878615")]
            public virtual RepoItemInfo ToiThấyHoaVangTrenCỏXanhInfo
            {
                get
                {
                    return _toithấyhoavangtrencỏxanhInfo;
                }
            }

            /// <summary>
            /// The SomeContainer3 item.
            /// </summary>
            [RepositoryItem("182493b6-736d-4e2c-8df1-17a4573b82e9")]
            public virtual Ranorex.Container SomeContainer3
            {
                get
                {
                    return _somecontainer3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer3 item info.
            /// </summary>
            [RepositoryItemInfo("182493b6-736d-4e2c-8df1-17a4573b82e9")]
            public virtual RepoItemInfo SomeContainer3Info
            {
                get
                {
                    return _somecontainer3Info;
                }
            }

            /// <summary>
            /// The SomeContainer4 item.
            /// </summary>
            [RepositoryItem("14cb6e34-68ea-4122-badd-5ecec9f3be6a")]
            public virtual Ranorex.Container SomeContainer4
            {
                get
                {
                    return _somecontainer4Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer4 item info.
            /// </summary>
            [RepositoryItemInfo("14cb6e34-68ea-4122-badd-5ecec9f3be6a")]
            public virtual RepoItemInfo SomeContainer4Info
            {
                get
                {
                    return _somecontainer4Info;
                }
            }

            /// <summary>
            /// The SomeContainer5 item.
            /// </summary>
            [RepositoryItem("ab0242ab-8e42-48b4-8822-d740a881674d")]
            public virtual Ranorex.Container SomeContainer5
            {
                get
                {
                    return _somecontainer5Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer5 item info.
            /// </summary>
            [RepositoryItemInfo("ab0242ab-8e42-48b4-8822-d740a881674d")]
            public virtual RepoItemInfo SomeContainer5Info
            {
                get
                {
                    return _somecontainer5Info;
                }
            }

            /// <summary>
            /// The SachMới item.
            /// </summary>
            [RepositoryItem("9c2cb7ab-f454-44cb-a73d-9a2e6cf9f4c5")]
            public virtual Ranorex.Text SachMới
            {
                get
                {
                    return _sachmớiInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SachMới item info.
            /// </summary>
            [RepositoryItemInfo("9c2cb7ab-f454-44cb-a73d-9a2e6cf9f4c5")]
            public virtual SachMớiInfoClass SachMớiInfo
            {
                get
                {
                    return _sachmớiInfo;
                }
            }

            /// <summary>
            /// The SomeElement3 item.
            /// </summary>
            [RepositoryItem("66af9f4e-bb76-49b6-9538-6b41893febaa")]
            public virtual Ranorex.Unknown SomeElement3
            {
                get
                {
                    return _someelement3Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement3 item info.
            /// </summary>
            [RepositoryItemInfo("66af9f4e-bb76-49b6-9538-6b41893febaa")]
            public virtual RepoItemInfo SomeElement3Info
            {
                get
                {
                    return _someelement3Info;
                }
            }

            /// <summary>
            /// The TenSach item.
            /// </summary>
            [RepositoryItem("b369f7df-c522-480d-b98e-99d5d93e2f8b")]
            public virtual Ranorex.Text TenSach
            {
                get
                {
                    return _tensachInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TenSach item info.
            /// </summary>
            [RepositoryItemInfo("b369f7df-c522-480d-b98e-99d5d93e2f8b")]
            public virtual RepoItemInfo TenSachInfo
            {
                get
                {
                    return _tensachInfo;
                }
            }

            /// <summary>
            /// The ToggleTemplateRoot item.
            /// </summary>
            [RepositoryItem("f1626129-8f81-46ea-bfe6-7ff855d09c8f")]
            public virtual Ranorex.Unknown ToggleTemplateRoot
            {
                get
                {
                    return _toggletemplaterootInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ToggleTemplateRoot item info.
            /// </summary>
            [RepositoryItemInfo("f1626129-8f81-46ea-bfe6-7ff855d09c8f")]
            public virtual RepoItemInfo ToggleTemplateRootInfo
            {
                get
                {
                    return _toggletemplaterootInfo;
                }
            }

            /// <summary>
            /// The TenTacGiả item.
            /// </summary>
            [RepositoryItem("f724989a-619b-4908-8466-27003022f38d")]
            public virtual Ranorex.Text TenTacGiả
            {
                get
                {
                    return _tentacgiảInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TenTacGiả item info.
            /// </summary>
            [RepositoryItemInfo("f724989a-619b-4908-8466-27003022f38d")]
            public virtual RepoItemInfo TenTacGiảInfo
            {
                get
                {
                    return _tentacgiảInfo;
                }
            }

            /// <summary>
            /// The ToggleTemplateRoot1 item.
            /// </summary>
            [RepositoryItem("3b6a31e9-0e35-4f01-af4a-d395ff261887")]
            public virtual Ranorex.Unknown ToggleTemplateRoot1
            {
                get
                {
                    return _toggletemplateroot1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ToggleTemplateRoot1 item info.
            /// </summary>
            [RepositoryItemInfo("3b6a31e9-0e35-4f01-af4a-d395ff261887")]
            public virtual RepoItemInfo ToggleTemplateRoot1Info
            {
                get
                {
                    return _toggletemplateroot1Info;
                }
            }

            /// <summary>
            /// The ToggleTemplateRoot2 item.
            /// </summary>
            [RepositoryItem("8e9b59ce-1ebc-40bf-8b5c-a2e10f482e52")]
            public virtual Ranorex.Unknown ToggleTemplateRoot2
            {
                get
                {
                    return _toggletemplateroot2Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ToggleTemplateRoot2 item info.
            /// </summary>
            [RepositoryItemInfo("8e9b59ce-1ebc-40bf-8b5c-a2e10f482e52")]
            public virtual RepoItemInfo ToggleTemplateRoot2Info
            {
                get
                {
                    return _toggletemplateroot2Info;
                }
            }

            /// <summary>
            /// The Text50000 item.
            /// </summary>
            [RepositoryItem("4d588659-1e53-41d5-b25a-a5d1e9c666df")]
            public virtual Ranorex.Text Text50000
            {
                get
                {
                    return _text50000Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text50000 item info.
            /// </summary>
            [RepositoryItemInfo("4d588659-1e53-41d5-b25a-a5d1e9c666df")]
            public virtual RepoItemInfo Text50000Info
            {
                get
                {
                    return _text50000Info;
                }
            }

            /// <summary>
            /// The SomeElement4 item.
            /// </summary>
            [RepositoryItem("dfa34568-bd8a-4e4c-a5ee-7a8cf94f4822")]
            public virtual Ranorex.Unknown SomeElement4
            {
                get
                {
                    return _someelement4Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement4 item info.
            /// </summary>
            [RepositoryItemInfo("dfa34568-bd8a-4e4c-a5ee-7a8cf94f4822")]
            public virtual RepoItemInfo SomeElement4Info
            {
                get
                {
                    return _someelement4Info;
                }
            }

            /// <summary>
            /// The SomeContainer6 item.
            /// </summary>
            [RepositoryItem("22b5bb61-0619-4a4e-96c8-7a7f86030c8e")]
            public virtual Ranorex.Container SomeContainer6
            {
                get
                {
                    return _somecontainer6Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer6 item info.
            /// </summary>
            [RepositoryItemInfo("22b5bb61-0619-4a4e-96c8-7a7f86030c8e")]
            public virtual RepoItemInfo SomeContainer6Info
            {
                get
                {
                    return _somecontainer6Info;
                }
            }

            /// <summary>
            /// The Pictures item.
            /// </summary>
            [RepositoryItem("983d6328-b834-4899-aea2-4665c311faf1")]
            public virtual Ranorex.TreeItem Pictures
            {
                get
                {
                    return _picturesInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Pictures item info.
            /// </summary>
            [RepositoryItemInfo("983d6328-b834-4899-aea2-4665c311faf1")]
            public virtual PicturesInfoClass PicturesInfo
            {
                get
                {
                    return _picturesInfo;
                }
            }

            /// <summary>
            /// The BaselineImage item.
            /// </summary>
            [RepositoryItem("c9029e1a-af51-4e87-97d1-f3e765790316")]
            public virtual Ranorex.Picture BaselineImage
            {
                get
                {
                    return _baselineimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The BaselineImage item info.
            /// </summary>
            [RepositoryItemInfo("c9029e1a-af51-4e87-97d1-f3e765790316")]
            public virtual BaselineImageInfoClass BaselineImageInfo
            {
                get
                {
                    return _baselineimageInfo;
                }
            }

            /// <summary>
            /// The Them item.
            /// </summary>
            [RepositoryItem("955aae91-2388-40bc-8feb-9b446b6deb02")]
            public virtual Ranorex.Text Them
            {
                get
                {
                    return _themInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Them item info.
            /// </summary>
            [RepositoryItemInfo("955aae91-2388-40bc-8feb-9b446b6deb02")]
            public virtual ThemInfoClass ThemInfo
            {
                get
                {
                    return _themInfo;
                }
            }

            /// <summary>
            /// The SomeContainer7 item.
            /// </summary>
            [RepositoryItem("bea66fb8-4515-46a3-92d5-d11bab30d942")]
            public virtual Ranorex.Container SomeContainer7
            {
                get
                {
                    return _somecontainer7Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer7 item info.
            /// </summary>
            [RepositoryItemInfo("bea66fb8-4515-46a3-92d5-d11bab30d942")]
            public virtual RepoItemInfo SomeContainer7Info
            {
                get
                {
                    return _somecontainer7Info;
                }
            }

            /// <summary>
            /// The SomeContainer8 item.
            /// </summary>
            [RepositoryItem("9f0f271e-f4b0-449a-b9ae-7396d4fc582c")]
            public virtual Ranorex.Container SomeContainer8
            {
                get
                {
                    return _somecontainer8Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer8 item info.
            /// </summary>
            [RepositoryItemInfo("9f0f271e-f4b0-449a-b9ae-7396d4fc582c")]
            public virtual RepoItemInfo SomeContainer8Info
            {
                get
                {
                    return _somecontainer8Info;
                }
            }

            /// <summary>
            /// The Border item.
            /// </summary>
            [RepositoryItem("9f5b10a7-e413-4289-ae5a-d74103cff468")]
            public virtual Ranorex.Unknown Border
            {
                get
                {
                    return _borderInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Border item info.
            /// </summary>
            [RepositoryItemInfo("9f5b10a7-e413-4289-ae5a-d74103cff468")]
            public virtual BorderInfoClass BorderInfo
            {
                get
                {
                    return _borderInfo;
                }
            }

            /// <summary>
            /// The SomeContainer9 item.
            /// </summary>
            [RepositoryItem("9154ca19-1086-439b-940d-528d7c683df6")]
            public virtual Ranorex.Container SomeContainer9
            {
                get
                {
                    return _somecontainer9Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer9 item info.
            /// </summary>
            [RepositoryItemInfo("9154ca19-1086-439b-940d-528d7c683df6")]
            public virtual SomeContainer9InfoClass SomeContainer9Info
            {
                get
                {
                    return _somecontainer9Info;
                }
            }

            /// <summary>
            /// The SomeContainer10 item.
            /// </summary>
            [RepositoryItem("4209e6ce-173c-4140-9483-42573f277a93")]
            public virtual Ranorex.Container SomeContainer10
            {
                get
                {
                    return _somecontainer10Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer10 item info.
            /// </summary>
            [RepositoryItemInfo("4209e6ce-173c-4140-9483-42573f277a93")]
            public virtual RepoItemInfo SomeContainer10Info
            {
                get
                {
                    return _somecontainer10Info;
                }
            }

            /// <summary>
            /// The SomeContainer11 item.
            /// </summary>
            [RepositoryItem("20e549b7-287f-4fa1-afa8-35a1085f242e")]
            public virtual Ranorex.Container SomeContainer11
            {
                get
                {
                    return _somecontainer11Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer11 item info.
            /// </summary>
            [RepositoryItemInfo("20e549b7-287f-4fa1-afa8-35a1085f242e")]
            public virtual RepoItemInfo SomeContainer11Info
            {
                get
                {
                    return _somecontainer11Info;
                }
            }

            /// <summary>
            /// The Pictures1 item.
            /// </summary>
            [RepositoryItem("c1b34755-02f1-4065-ae89-6aee094f6d1a")]
            public virtual Ranorex.TreeItem Pictures1
            {
                get
                {
                    return _pictures1Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Pictures1 item info.
            /// </summary>
            [RepositoryItemInfo("c1b34755-02f1-4065-ae89-6aee094f6d1a")]
            public virtual RepoItemInfo Pictures1Info
            {
                get
                {
                    return _pictures1Info;
                }
            }
        }

        /// <summary>
        /// The BookStoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4180362-6a84-4556-9da7-83dbc77601a9")]
        public partial class BookStoreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _somecontainerInfo;

            /// <summary>
            /// Creates a new BookStore  folder.
            /// </summary>
            public BookStoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BookStore", "/contextmenu[@processname='BookStore' and @win32ownerwindowlevel='1']", parentFolder, 3000, null, false, "a4180362-6a84-4556-9da7-83dbc77601a9", "")
            {
                _somecontainerInfo = new RepoItemInfo(this, "SomeContainer", ".//container/container/container/container", 3000, null, "efb97873-2d67-48e0-8512-351691e942ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4180362-6a84-4556-9da7-83dbc77601a9")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4180362-6a84-4556-9da7-83dbc77601a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeContainer item.
            /// </summary>
            [RepositoryItem("efb97873-2d67-48e0-8512-351691e942ef")]
            public virtual Ranorex.Container SomeContainer
            {
                get
                {
                    return _somecontainerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SomeContainer item info.
            /// </summary>
            [RepositoryItemInfo("efb97873-2d67-48e0-8512-351691e942ef")]
            public virtual RepoItemInfo SomeContainerInfo
            {
                get
                {
                    return _somecontainerInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}