///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BookStoreTest.LoginRecord
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The baseRecord recording.
    /// </summary>
    [TestModule("5846458e-0169-4fcc-8f1a-511b6daf66be", ModuleType.Recording, 1)]
    public partial class baseRecord : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BookStoreTest.BookStoreTestRepository repository.
        /// </summary>
        public static global::BookStoreTest.BookStoreTestRepository repo = global::BookStoreTest.BookStoreTestRepository.Instance;

        static baseRecord instance = new baseRecord();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public baseRecord()
        {
            txtErrorMess = "Mật hoặc tài khoản không đúng";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static baseRecord Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable txtErrorMess.
        /// </summary>
        [TestVariable("30c6c61f-7769-4f07-aafc-cb55c8ffbed4")]
        public string txtErrorMess
        {
            get { return repo.txtErrorMess; }
            set { repo.txtErrorMess = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeContainer' at 158;9.", repo.ApplicationUnderTest.SomeContainer1.SomeContainerInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer.Click("158;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.TimKiếm' at 45;14.", repo.ApplicationUnderTest.SomeContainer1.TimKiếmInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SomeContainer1.TimKiếm.Click("45;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}'.", new RecordItemIndex(2));
            Keyboard.Press("{Back}{Back}{Back}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'toi thay'.", new RecordItemIndex(3));
            Keyboard.Press("toi thay");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}nh'.", new RecordItemIndex(4));
            Keyboard.Press("{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Back}nh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeContainer2' at 64;22.", repo.ApplicationUnderTest.SomeContainer1.SomeContainer2Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer2.Click("64;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LWin down}s{LWin up}'.", new RecordItemIndex(6));
            Keyboard.Press("{LWin down}s{LWin up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'sql'.", new RecordItemIndex(7));
            Keyboard.Press("sql");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomePicture' at 100;131.", repo.ApplicationUnderTest.SomeContainer1.SomePictureInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.SomeContainer1.SomePicture.Click("100;131");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.ToiThấyHoaVangTrenCỏXanh' at 184;22.", repo.ApplicationUnderTest.SomeContainer1.ToiThấyHoaVangTrenCỏXanhInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.SomeContainer1.ToiThấyHoaVangTrenCỏXanh.Click("184;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeContainer3' at 71;25.", repo.ApplicationUnderTest.SomeContainer1.SomeContainer3Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer3.Click("71;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(11));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 360 units.", new RecordItemIndex(12));
            Mouse.ScrollWheel(360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.SomeContainer1.SomeContainer4' at 10;366.", repo.ApplicationUnderTest.SomeContainer1.SomeContainer4Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer4.DoubleClick("10;366");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Ckey}{LControlKey up}'.", new RecordItemIndex(14));
            Keyboard.Press("{LControlKey down}{Ckey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.SomeContainer1.TimKiếm' at 19;10.", repo.ApplicationUnderTest.SomeContainer1.TimKiếmInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.SomeContainer1.TimKiếm.MoveTo("19;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Vkey}{LControlKey up}'.", new RecordItemIndex(16));
            Keyboard.Press("{LControlKey down}{Vkey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeContainer2' at 68;20.", repo.ApplicationUnderTest.SomeContainer1.SomeContainer2Info, new RecordItemIndex(17));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer2.Click("68;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeElement2' at 121;7.", repo.ApplicationUnderTest.SomeContainer1.SomeElement2Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.SomeContainer1.SomeElement2.Click("121;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 14}{Back}nh'.", new RecordItemIndex(19));
            Keyboard.Press("{Back 14}{Back}nh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeContainer2' at 65;18.", repo.ApplicationUnderTest.SomeContainer1.SomeContainer2Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer2.Click("65;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
