///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BookStoreTest.LoginRecord
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateButtonEnable recording.
    /// </summary>
    [TestModule("9040dd68-34c7-4dfe-935a-7bf0c433192a", ModuleType.Recording, 1)]
    public partial class ValidateButtonEnable : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BookStoreTest.BookStoreTestRepository repository.
        /// </summary>
        public static global::BookStoreTest.BookStoreTestRepository repo = global::BookStoreTest.BookStoreTestRepository.Instance;

        static ValidateButtonEnable instance = new ValidateButtonEnable();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateButtonEnable()
        {
            btn_check = "False";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateButtonEnable Instance
        {
            get { return instance; }
        }

#region Variables

        string _btn_check;

        /// <summary>
        /// Gets or sets the value of variable btn_check.
        /// </summary>
        [TestVariable("fae58463-7109-4c91-a7a2-3d7a3a64cd71")]
        public string btn_check
        {
            get { return _btn_check; }
            set { _btn_check = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Enabled~$btn_check) on item 'ApplicationUnderTest.Button'.", repo.ApplicationUnderTest.ButtonInfo, new RecordItemIndex(0));
            Validate.AttributeRegex(repo.ApplicationUnderTest.ButtonInfo, "Enabled", new Regex(btn_check));
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
