///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BookStoreTest.LoginRecord
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateErrorMess_3 recording.
    /// </summary>
    [TestModule("20b220a3-c5b2-41d4-b198-2ac0e4a2327f", ModuleType.Recording, 1)]
    public partial class validateErrorMess_3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BookStoreTest.BookStoreTestRepository repository.
        /// </summary>
        public static global::BookStoreTest.BookStoreTestRepository repo = global::BookStoreTest.BookStoreTestRepository.Instance;

        static validateErrorMess_3 instance = new validateErrorMess_3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateErrorMess_3()
        {
            txtErrorMess = "Mật hoặc tài khoản không đúng";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateErrorMess_3 Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable txtErrorMess.
        /// </summary>
        [TestVariable("f95e450a-ba0d-4af3-866b-94671c0eb3e3")]
        public string txtErrorMess
        {
            get { return repo.txtErrorMess; }
            set { repo.txtErrorMess = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$txtErrorMess) on item 'ApplicationUnderTest.SomeContainer1.MậtHoặcTaiKhoảnKhongĐung'.", repo.ApplicationUnderTest.SomeContainer1.MậtHoặcTaiKhoảnKhongĐungInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.ApplicationUnderTest.SomeContainer1.MậtHoặcTaiKhoảnKhongĐungInfo, "Text", txtErrorMess);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
