///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BookStoreTest.LoginRecord
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateErrorMess recording.
    /// </summary>
    [TestModule("28d82d1c-4618-429a-9dcb-0d9f031f5106", ModuleType.Recording, 1)]
    public partial class validateErrorMess : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BookStoreTest.BookStoreTestRepository repository.
        /// </summary>
        public static global::BookStoreTest.BookStoreTestRepository repo = global::BookStoreTest.BookStoreTestRepository.Instance;

        static validateErrorMess instance = new validateErrorMess();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateErrorMess()
        {
            txtErrorMess = "Mật hoặc tài khoản không đúng";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateErrorMess Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable txtErrorMess.
        /// </summary>
        [TestVariable("925b768a-5c4e-4435-a77d-d96bc2c1e3c3")]
        public string txtErrorMess
        {
            get { return repo.txtErrorMess; }
            set { repo.txtErrorMess = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$txtErrorMess) on item 'ApplicationUnderTest.MậtHoặcTaiKhoảnKhongĐung'.", repo.ApplicationUnderTest.MậtHoặcTaiKhoảnKhongĐungInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.MậtHoặcTaiKhoảnKhongĐungInfo, "Text", txtErrorMess);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
