///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BookStoreTest.addBookRecord
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The clickIntoBookWareHouse recording.
    /// </summary>
    [TestModule("447f7142-2e0c-4352-bc8b-6bbee95038ab", ModuleType.Recording, 1)]
    public partial class clickIntoBookWareHouse : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::BookStoreTest.BookStoreTestRepository repository.
        /// </summary>
        public static global::BookStoreTest.BookStoreTestRepository repo = global::BookStoreTest.BookStoreTestRepository.Instance;

        static clickIntoBookWareHouse instance = new clickIntoBookWareHouse();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public clickIntoBookWareHouse()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static clickIntoBookWareHouse Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeContainer1.SomeContainer9' at 4;4.", repo.ApplicationUnderTest.SomeContainer1.SomeContainer9Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeContainer1.SomeContainer9.Click(new Location(SomeContainer9_Screenshot1, "4;4", SomeContainer9_Screenshot1_Options));
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage SomeContainer9_Screenshot1
        { get { return repo.ApplicationUnderTest.SomeContainer1.SomeContainer9Info.GetScreenshot1(new Rectangle(46, 34, 8, 8)); } }

        Imaging.FindOptions SomeContainer9_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
